# Generated by Django 5.1.1 on 2024-09-16 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_centre', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='devicesales',
            options={'verbose_name': 'Device Sale'},
        ),
        migrations.AlterModelOptions(
            name='productname',
            options={'verbose_name': 'Product List'},
        ),
        migrations.AlterModelOptions(
            name='specifications',
            options={'verbose_name': 'Product Specifications'},
        ),
        migrations.AlterModelOptions(
            name='stockslist',
            options={'verbose_name': 'Device Stock'},
        ),
        migrations.AlterField(
            model_name='devicesales',
            name='sales_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 16, 17, 42, 10, 734567, tzinfo=datetime.timezone.utc), verbose_name='Sales Date'),
        ),
        migrations.AlterField(
            model_name='productname',
            name='eol_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 15, 20, 42, 10, 729551)),
        ),
    ]
