# Generated by Django 5.1.1 on 2025-04-19 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_centre', '0002_alter_brands_options_alter_devicesales_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='devicesales',
            options={'verbose_name_plural': 'Device Sale'},
        ),
        migrations.AlterModelOptions(
            name='productname',
            options={'verbose_name_plural': 'Product List'},
        ),
        migrations.AlterModelOptions(
            name='specifications',
            options={'verbose_name_plural': 'Product Specifications'},
        ),
        migrations.AlterModelOptions(
            name='stockslist',
            options={'verbose_name_plural': 'Device Stock'},
        ),
        migrations.AlterField(
            model_name='devicesales',
            name='sales_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 19, 5, 43, 16, 190433, tzinfo=datetime.timezone.utc), verbose_name='Sales Date'),
        ),
        migrations.AlterField(
            model_name='productname',
            name='eol_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 16, 8, 43, 16, 190433)),
        ),
    ]
