# Generated by Django 5.1.1 on 2025-04-19 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_centre', '0003_alter_brands_options_alter_devicesales_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesales',
            name='sales_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 19, 8, 18, 52, 217578, tzinfo=datetime.timezone.utc), verbose_name='Sales Date'),
        ),
        migrations.AlterField(
            model_name='productname',
            name='eol_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 16, 11, 18, 52, 215575)),
        ),
    ]
