# Generated by Django 5.1.1 on 2025-04-19 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_centre', '0004_alter_devicesales_sales_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesales',
            name='sales_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 19, 8, 58, 23, 231295, tzinfo=datetime.timezone.utc), verbose_name='Sales Date'),
        ),
        migrations.AlterField(
            model_name='productname',
            name='eol_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 16, 11, 58, 23, 231295)),
        ),
    ]
