# Generated by Django 5.1.2 on 2025-07-21 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_centre', '0005_alter_devicesales_sales_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesales',
            name='sales_date',
            field=models.DateField(default=datetime.datetime(2025, 7, 21, 17, 37, 15, 26249, tzinfo=datetime.timezone.utc), verbose_name='Sales Date'),
        ),
        migrations.AlterField(
            model_name='productname',
            name='eol_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 17, 20, 37, 15, 23249)),
        ),
    ]
