# Generated by Django 5.1.2 on 2025-07-23 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_centre', '0008_alter_devicesales_sales_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesales',
            name='sales_date',
            field=models.DateField(default=datetime.datetime(2025, 7, 23, 20, 3, 35, 406701, tzinfo=datetime.timezone.utc), verbose_name='Sales Date'),
        ),
        migrations.AlterField(
            model_name='productname',
            name='eol_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 19, 23, 3, 35, 405701)),
        ),
    ]
