# Generated by Django 5.1.2 on 2025-08-07 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_centre', '0013_alter_devicesales_sales_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesales',
            name='sales_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 7, 18, 45, 55, 565823, tzinfo=datetime.timezone.utc), verbose_name='Sales Date'),
        ),
        migrations.AlterField(
            model_name='productname',
            name='eol_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 3, 21, 45, 55, 564770)),
        ),
    ]
