# Generated by Django 4.1.6 on 2023-09-09 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('contact_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('cost', models.FloatField()),
                ('sent_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('this_user', models.CharField(max_length=100)),
                ('wallet', models.FloatField()),
                ('limit', models.FloatField(default=1000.0)),
                ('current', models.FloatField(default=0.0)),
            ],
        ),
    ]
