# Generated by Django 4.1.6 on 2023-09-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='contact_file',
            field=models.FileField(default='contacts.xlsx', upload_to='contact_files'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='contact_mode',
            field=models.CharField(choices=[('file', 'file'), ('single', 'single')], default='single', max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_number',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='current_user',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
