# Generated by Django 4.1.6 on 2023-09-10 11:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_contacts_contact_file_contacts_contact_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentrecord',
            name='creator',
            field=models.CharField(default='koshtech', max_length=100),
        ),
        migrations.AlterField(
            model_name='sentrecord',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
