# Generated by Django 4.1.4 on 2023-01-09 12:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_cat', models.CharField(max_length=100)),
                ('shop_loc', models.CharField(max_length=100)),
                ('shop_created', models.DateTimeField(default=datetime.datetime(2023, 1, 9, 12, 24, 56, 678962, tzinfo=datetime.timezone.utc))),
                ('shop_auth', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('t_id', models.IntegerField(primary_key=True, serialize=False)),
                ('t_serial', models.CharField(max_length=100)),
                ('t_name', models.CharField(max_length=100)),
                ('t_from', models.CharField(max_length=100)),
                ('t_to', models.CharField(max_length=100)),
                ('t_qty', models.IntegerField()),
                ('t_created', models.DateTimeField(default=datetime.datetime(2023, 1, 9, 12, 24, 56, 682103, tzinfo=datetime.timezone.utc))),
                ('t_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_serial', models.CharField(default='No serial', max_length=100)),
                ('p_name', models.CharField(max_length=100)),
                ('p_category', models.CharField(max_length=100)),
                ('p_desc', models.TextField()),
                ('p_image', models.ImageField(default='product.jpg', upload_to='stocks_images')),
                ('p_qty', models.IntegerField()),
                ('p_price', models.FloatField()),
                ('p_cost', models.FloatField()),
                ('p_created', models.DateTimeField(default=datetime.datetime(2023, 1, 9, 12, 24, 56, 680138, tzinfo=datetime.timezone.utc))),
                ('p_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('p_shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.shops')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_serial', models.CharField(max_length=100)),
                ('s_name', models.CharField(max_length=100)),
                ('s_price', models.FloatField()),
                ('s_cost', models.FloatField()),
                ('s_negatives', models.FloatField()),
                ('s_profit', models.FloatField()),
                ('s_created', models.DateTimeField(default=datetime.datetime(2023, 1, 9, 12, 24, 56, 680870, tzinfo=datetime.timezone.utc))),
                ('s_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('s_shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.shops')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('exp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('exp_desc', models.TextField()),
                ('exp_amount', models.FloatField()),
                ('exp_date', models.DateTimeField(default=datetime.datetime(2023, 1, 9, 12, 24, 56, 681463, tzinfo=datetime.timezone.utc))),
                ('exp_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('exp_shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.shops')),
            ],
        ),
    ]
