# Generated by Django 4.1.4 on 2023-02-18 07:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_cat', models.CharField(max_length=100)),
                ('shop_loc', models.CharField(max_length=100)),
                ('shop_created', models.DateTimeField(default=datetime.datetime(2023, 2, 18, 7, 38, 5, 434547))),
                ('shop_auth', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_serial', models.CharField(max_length=100)),
                ('t_name', models.CharField(max_length=100)),
                ('t_from', models.CharField(max_length=100)),
                ('t_to', models.CharField(max_length=100)),
                ('t_qty', models.IntegerField()),
                ('t_created', models.DateTimeField(default=datetime.datetime(2023, 2, 18, 7, 38, 5, 437837))),
                ('t_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=1000)),
                ('task_desc', models.TextField()),
                ('task_status', models.CharField(max_length=1000)),
                ('task_creator', models.CharField(max_length=1000)),
                ('task_created', models.DateTimeField(default=datetime.datetime(2023, 2, 18, 7, 38, 5, 438822))),
                ('task_to', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_gen', models.IntegerField(default=-7735739788060953324)),
                ('p_serial', models.CharField(default='No serial', max_length=100)),
                ('p_name', models.CharField(max_length=100)),
                ('p_category', models.CharField(max_length=100)),
                ('p_desc', models.TextField()),
                ('p_image', models.ImageField(default='product.jpg', upload_to='stocks_images')),
                ('p_qty', models.IntegerField()),
                ('p_price', models.FloatField()),
                ('p_cost', models.FloatField()),
                ('p_vat', models.FloatField(default=0.0)),
                ('p_disc', models.FloatField(default=0.0)),
                ('p_created', models.DateTimeField(default=datetime.datetime(2023, 2, 18, 7, 38, 5, 435737))),
                ('p_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('p_shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.shops')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_serial', models.CharField(max_length=100)),
                ('s_name', models.CharField(max_length=100)),
                ('s_qty', models.FloatField()),
                ('s_price', models.FloatField()),
                ('s_cost', models.FloatField()),
                ('s_negatives', models.FloatField()),
                ('s_profit', models.FloatField()),
                ('s_type', models.CharField(default='cash', max_length=100)),
                ('s_status', models.CharField(default='sold', max_length=100)),
                ('s_created', models.DateTimeField(default=datetime.datetime(2023, 2, 18, 7, 38, 5, 436591))),
                ('s_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('s_shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.shops')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=100000)),
                ('longitude', models.CharField(default=0.0, max_length=100000)),
                ('loc_tag', models.CharField(default='not set', max_length=100)),
                ('loc_created', models.DateTimeField(default=datetime.datetime(2023, 2, 18, 7, 38, 5, 438351))),
                ('loc_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('exp_id', models.AutoField(primary_key=True, serialize=False)),
                ('exp_desc', models.TextField()),
                ('exp_amount', models.FloatField()),
                ('exp_date', models.DateTimeField(default=datetime.datetime(2023, 2, 18, 7, 38, 5, 437310))),
                ('exp_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('exp_shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.shops')),
            ],
        ),
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('debt_id', models.AutoField(primary_key=True, serialize=False)),
                ('debt_cus', models.CharField(max_length=1000)),
                ('debt_amnt', models.FloatField(default=0.0)),
                ('debt_rem', models.FloatField(default=0.0)),
                ('debt_last', models.DateTimeField(default=datetime.datetime(2023, 2, 18, 7, 38, 5, 439900))),
                ('debt_remks', models.TextField()),
                ('debt_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
