# Generated by Django 4.1.4 on 2022-12-12 18:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=100)),
                ('p_category', models.CharField(max_length=100)),
                ('p_desc', models.TextField()),
                ('p_image', models.CharField(max_length=1000)),
                ('p_qty', models.IntegerField()),
                ('p_price', models.FloatField()),
                ('p_cost', models.FloatField()),
                ('p_created', models.DateTimeField(default=datetime.datetime(2022, 12, 12, 18, 26, 27, 841120, tzinfo=datetime.timezone.utc))),
                ('p_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
