# Generated by Django 4.1.6 on 2023-02-12 04:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='exp_shop',
        ),
        migrations.AddField(
            model_name='sales',
            name='s_qty',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='s_status',
            field=models.CharField(default='sold', max_length=100),
        ),
        migrations.AddField(
            model_name='sales',
            name='s_type',
            field=models.CharField(default='cash', max_length=100),
        ),
        migrations.AddField(
            model_name='stocks',
            name='p_disc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stocks',
            name='p_gen',
            field=models.IntegerField(default=9161554859088404104),
        ),
        migrations.AddField(
            model_name='stocks',
            name='p_vat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 4, 30, 2, 223913)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sales',
            name='s_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 4, 30, 2, 223115)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='s_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shops',
            name='shop_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 4, 30, 2, 221103)),
        ),
        migrations.AlterField(
            model_name='shops',
            name='shop_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 4, 30, 2, 222290)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='t_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 4, 30, 2, 224475)),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='t_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=1000)),
                ('task_desc', models.TextField()),
                ('task_status', models.CharField(max_length=1000)),
                ('task_creator', models.CharField(max_length=1000)),
                ('task_created', models.DateTimeField(default=datetime.datetime(2023, 2, 12, 4, 30, 2, 225469))),
                ('task_to', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=100000)),
                ('longitude', models.CharField(default=0.0, max_length=100000)),
                ('loc_tag', models.CharField(default='not set', max_length=100)),
                ('loc_created', models.DateTimeField(default=datetime.datetime(2023, 2, 12, 4, 30, 2, 224986))),
                ('loc_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('debt_id', models.AutoField(primary_key=True, serialize=False)),
                ('debt_cus', models.CharField(max_length=1000)),
                ('debt_phone', models.CharField(max_length=100)),
                ('debt_amnt', models.FloatField(default=0.0)),
                ('debt_rem', models.FloatField(default=0.0)),
                ('debt_last', models.DateTimeField(default=datetime.datetime(2023, 2, 12, 4, 30, 2, 226530))),
                ('debt_remks', models.TextField()),
                ('debt_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
