# Generated by Django 4.1.4 on 2022-12-12 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='p_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 18, 27, 38, 428515, tzinfo=datetime.timezone.utc)),
        ),
    ]
