# Generated by Django 4.1.4 on 2023-01-28 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='exp_shop',
        ),
        migrations.AddField(
            model_name='sales',
            name='s_qty',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 8, 37, 51, 99935, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sales',
            name='s_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 8, 37, 51, 99349, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='s_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shops',
            name='shop_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 8, 37, 51, 97263, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='shops',
            name='shop_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 8, 37, 51, 98468, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='t_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 8, 37, 51, 100545, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='t_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
