# Generated by Django 4.1.4 on 2022-12-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_stocks_p_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='p_created',
            field=models.DateTimeField(),
        ),
    ]
