# Generated by Django 4.1.4 on 2022-12-28 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_stocks_p_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='p_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 21, 29, 5, 842990, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_image',
            field=models.ImageField(default='product.jpg', upload_to='stocks_images'),
        ),
    ]
