# Generated by Django 4.1.6 on 2023-05-21 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_debts_debt_last_alter_expenses_exp_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debts',
            name='debt_last',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 11, 34, 54, 792176)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 11, 34, 54, 790185)),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 11, 34, 54, 791178)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='s_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 11, 34, 54, 790185)),
        ),
        migrations.AlterField(
            model_name='shops',
            name='shop_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 11, 34, 54, 788189)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 11, 34, 54, 789157)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.IntegerField(default=-5952925623285193769),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 11, 34, 54, 791178)),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='t_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 11, 34, 54, 790185)),
        ),
    ]
