# Generated by Django 4.1.6 on 2023-05-31 10:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0004_alter_debts_debt_last_alter_expenses_exp_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debts',
            name='debt_last',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 13, 34, 21, 82348)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 13, 34, 21, 66726)),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 13, 34, 21, 82348)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='s_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 13, 34, 21, 66726)),
        ),
        migrations.AlterField(
            model_name='shops',
            name='shop_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 13, 34, 21, 66726)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 13, 34, 21, 66726)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.IntegerField(default=5782924905517126409),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 13, 34, 21, 82348)),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='t_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 13, 34, 21, 82348)),
        ),
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('qty', models.FloatField()),
                ('amount', models.FloatField()),
                ('profit', models.FloatField()),
                ('pay_type', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 5, 31, 13, 34, 21, 66726))),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
