# Generated by Django 4.1.4 on 2023-01-01 14:54

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0004_alter_stocks_p_created_alter_stocks_p_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='p_serial',
            field=models.CharField(default='No serial', max_length=100),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 14, 54, 38, 948735, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_cat', models.CharField(max_length=100)),
                ('shop_loc', models.CharField(max_length=100)),
                ('shop_created', models.DateTimeField(default=datetime.datetime(2023, 1, 1, 14, 54, 38, 947505, tzinfo=datetime.timezone.utc))),
                ('shop_auth', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
