# Generated by Django 4.1.5 on 2023-02-02 13:40

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0008_alter_expenses_exp_date_alter_location_loc_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 16, 40, 23, 561010)),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 16, 40, 23, 561010)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='s_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 16, 40, 23, 561010)),
        ),
        migrations.AlterField(
            model_name='shops',
            name='shop_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 16, 40, 23, 561010)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 16, 40, 23, 561010)),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='t_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 16, 40, 23, 561010)),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=1000)),
                ('task_desc', models.TextField()),
                ('task_status', models.CharField(max_length=1000)),
                ('task_creator', models.CharField(max_length=1000)),
                ('task_created', models.DateTimeField(default=datetime.datetime(2023, 2, 2, 16, 40, 23, 570947))),
                ('task_to', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
