# Generated by Django 4.1.6 on 2023-07-18 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_alter_contacts_cont_created_alter_debts_debt_last_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='cont_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 3, 47, 377091)),
        ),
        migrations.AlterField(
            model_name='debts',
            name='debt_last',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 3, 47, 376609)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 3, 47, 373950)),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 3, 47, 374961)),
        ),
        migrations.AlterField(
            model_name='paid',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 3, 47, 373386)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='s_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 3, 47, 372674)),
        ),
        migrations.AlterField(
            model_name='shops',
            name='shop_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 3, 47, 370587)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 3, 47, 371831)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.IntegerField(default=759624422158797690),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 3, 47, 375468)),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='t_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 3, 47, 374443)),
        ),
    ]
