# Generated by Django 4.1.6 on 2023-07-18 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_alter_contacts_cont_created_alter_debts_debt_last_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='cont_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 57, 35, 582973)),
        ),
        migrations.AlterField(
            model_name='debts',
            name='debt_last',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 57, 35, 582452)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 57, 35, 579412)),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 57, 35, 580590)),
        ),
        migrations.AlterField(
            model_name='paid',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 57, 35, 578844)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='s_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 57, 35, 578082)),
        ),
        migrations.AlterField(
            model_name='shops',
            name='shop_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 57, 35, 576036)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 57, 35, 577268)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.BigIntegerField(default=-5478713963019259809),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 57, 35, 581132)),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='t_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 57, 35, 579987)),
        ),
    ]
