# Generated by Django 4.1.4 on 2023-02-08 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_sales_s_status_alter_expenses_exp_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='s_type',
            field=models.CharField(default='cash', max_length=100),
        ),
        migrations.AddField(
            model_name='stocks',
            name='p_disc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stocks',
            name='p_vat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 10, 4, 24, 830920)),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 10, 4, 24, 831937)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='s_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 10, 4, 24, 830212)),
        ),
        migrations.AlterField(
            model_name='shops',
            name='shop_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 10, 4, 24, 828193)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 10, 4, 24, 829414)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 10, 4, 24, 832427)),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='t_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 10, 4, 24, 831424)),
        ),
    ]
