# Generated by Django 4.1.6 on 2023-07-19 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_alter_contacts_cont_created_alter_debts_debt_last_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mpesaPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contacts',
            name='cont_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 9, 57, 37, 609528)),
        ),
        migrations.AlterField(
            model_name='debts',
            name='debt_last',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 9, 57, 37, 608865)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 9, 57, 37, 605712)),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 9, 57, 37, 607067)),
        ),
        migrations.AlterField(
            model_name='paid',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 9, 57, 37, 604670)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='s_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 9, 57, 37, 603851)),
        ),
        migrations.AlterField(
            model_name='shops',
            name='shop_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 9, 57, 37, 601056)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 9, 57, 37, 602611)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.BigIntegerField(default=6311912718942414361),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 9, 57, 37, 607766)),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='t_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 9, 57, 37, 606367)),
        ),
    ]
