# Generated by Django 4.1.6 on 2023-07-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_mpesapay_amount_mpesapay_date_mpesapay_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.BigIntegerField(default=8785197351262),
        ),
    ]
