# Generated by Django 4.1.6 on 2023-07-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_alter_stocks_p_gen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.BigIntegerField(default=8767745517662),
        ),
    ]
