# Generated by Django 4.2.5 on 2024-02-29 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0023_alter_stocks_p_gen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.BigIntegerField(default=133806346955),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=1.0, null=True)),
                ('cart_stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.stocks')),
            ],
        ),
    ]
