# Generated by Django 4.2.5 on 2024-03-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0024_alter_stocks_p_gen_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=200.0, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.BigIntegerField(default=125233971915),
        ),
    ]
