# Generated by Django 4.2.5 on 2024-03-02 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0025_cart_price_alter_stocks_p_gen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='s_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shops'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.BigIntegerField(default=165639553712),
        ),
    ]
