# Generated by Django 5.1.1 on 2024-09-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0027_alter_stocks_p_gen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.BigIntegerField(default=136722879672),
        ),
    ]
