# Generated by Django 5.1.1 on 2024-09-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0029_alter_stocks_p_gen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Customer Contacts'},
        ),
        migrations.AlterModelOptions(
            name='debts',
            options={'verbose_name': 'Debt List'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='mpesapay',
            options={'verbose_name': 'Mpesa Payments'},
        ),
        migrations.AlterModelOptions(
            name='paid',
            options={'verbose_name': 'Paid Products'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='shops',
            options={'verbose_name': 'Shops'},
        ),
        migrations.AlterModelOptions(
            name='stocks',
            options={'verbose_name': 'Stocks'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.BigIntegerField(default=132504197304),
        ),
    ]
