# Generated by Django 5.1.1 on 2025-04-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0030_alter_contacts_options_alter_debts_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Customer Contacts'},
        ),
        migrations.AlterModelOptions(
            name='debts',
            options={'verbose_name_plural': 'Debt List'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='mpesapay',
            options={'verbose_name_plural': 'Mpesa Payments'},
        ),
        migrations.AlterModelOptions(
            name='paid',
            options={'verbose_name_plural': 'Paid Products'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='shops',
            options={'verbose_name_plural': 'Shops'},
        ),
        migrations.AlterModelOptions(
            name='stocks',
            options={'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='transfers',
            options={'verbose_name_plural': 'Transfers'},
        ),
        migrations.AddField(
            model_name='cart',
            name='order_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='shop_terms',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.BigIntegerField(default=124127614196),
        ),
    ]
