# Generated by Django 5.1.1 on 2025-04-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0031_alter_contacts_options_alter_debts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='shop_terms',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.BigIntegerField(default=148198286580),
        ),
    ]
