# Generated by Django 5.1.1 on 2025-04-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0032_alter_shops_shop_terms_alter_stocks_p_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='s_order_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.BigIntegerField(default=165201855732),
        ),
    ]
