# Generated by Django 5.1.2 on 2025-07-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0033_sales_s_order_code_alter_stocks_p_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='adjust_price',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.BigIntegerField(default=125433201164),
        ),
    ]
