# Generated by Django 5.1.2 on 2025-07-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0035_cart_user_alter_stocks_p_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='initial_price',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.BigIntegerField(default=131891381772),
        ),
    ]
