# Generated by Django 5.1.2 on 2025-08-07 17:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0038_alter_stocks_p_gen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.BigIntegerField(default=126747337972),
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('i_code', models.CharField(max_length=100)),
                ('i_serial', models.CharField(max_length=100)),
                ('i_name', models.CharField(max_length=100)),
                ('i_qty', models.FloatField()),
                ('i_price', models.FloatField()),
                ('i_cost', models.FloatField()),
                ('i_discount', models.FloatField()),
                ('i_profit', models.FloatField()),
                ('i_type', models.CharField(max_length=100)),
                ('i_status', models.CharField(max_length=100)),
                ('i_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('i_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('i_shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.shops')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=100)),
                ('org_details', models.TextField()),
                ('org_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('logo', models.ImageField(default='product.jpg', upload_to='orgs_images')),
                ('org_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Organisation',
            },
        ),
    ]
