# Generated by Django 5.1.2 on 2025-08-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0039_alter_stocks_p_gen_invoices_organisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoices',
            options={'verbose_name_plural': 'Invoices'},
        ),
        migrations.AddField(
            model_name='organisation',
            name='org_summary_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.BigIntegerField(default=122528654580),
        ),
    ]
