# Generated by Django 5.1.2 on 2025-08-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0040_alter_invoices_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.BigIntegerField(default=141412066548),
        ),
    ]
