# Generated by Django 5.1.2 on 2025-08-07 18:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0041_alter_stocks_p_gen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='p_gen',
            field=models.BigIntegerField(default=118828623092),
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_name', models.CharField(max_length=100)),
                ('cus_phone', models.CharField(max_length=100)),
                ('cus_email', models.CharField(max_length=100)),
                ('cus_address', models.CharField(max_length=100)),
                ('cus_details', models.TextField()),
                ('cus_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('cus_ref_code', models.CharField(blank=True, max_length=100, null=True)),
                ('cus_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
