# Generated by Django 4.1.4 on 2022-12-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='first',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
